export interface PRDashboardData {
  No: number
  subject: string
  link: string
  label: string
  body: string | null
  summary: string | null
  stance_val: number
  assert_val: number
  category: string
  priority: string
  [key: string]: any
}

export const samplePRData: PRDashboardData[] = [
  {
    No: 1,
    subject: "typo fixed_row37",
    link: "https://github.com/team-mirai/policy/pull/1",
    label: "科学技術",
    body: null,
    summary: null,
    stance_val: 0,
    assert_val: 0,
    category: "中立",
    priority: "Low",
    flag_positive: false,
    flag_negative: false,
    flag_neutral: true,
    flag_strong: false,
    flag_moderate: false,
    flag_weak: false,
    flag_assertive: false,
    flag_mild: true,
    flag_uncertain: false
  },
  {
    No: 2,
    subject: "政策提案の改善",
    link: "https://github.com/team-mirai/policy/pull/2",
    label: "経済政策",
    body: null,
    summary: null,
    stance_val: 2.5,
    assert_val: 3.0,
    category: "肯定的",
    priority: "Medium",
    flag_positive: true,
    flag_negative: false,
    flag_neutral: false,
    flag_strong: false,
    flag_moderate: true,
    flag_weak: false,
    flag_assertive: true,
    flag_mild: false,
    flag_uncertain: false
  },
  {
    No: 108,
    subject: "教育制度の見直し",
    link: "https://github.com/team-mirai/policy/pull/108",
    label: "教育",
    body: null,
    summary: null,
    stance_val: -1.5,
    assert_val: 2.0,
    category: "否定的",
    priority: "High",
    flag_positive: false,
    flag_negative: true,
    flag_neutral: false,
    flag_strong: false,
    flag_moderate: true,
    flag_weak: false,
    flag_assertive: true,
    flag_mild: false,
    flag_uncertain: false
  },
  {
    No: 1000,
    subject: "記念すべき政策提案",
    link: "https://github.com/team-mirai/policy/pull/1000",
    label: "社会保障",
    body: null,
    summary: null,
    stance_val: 4.0,
    assert_val: 4.5,
    category: "強い肯定",
    priority: "High",
    flag_positive: true,
    flag_negative: false,
    flag_neutral: false,
    flag_strong: true,
    flag_moderate: false,
    flag_weak: false,
    flag_assertive: true,
    flag_mild: false,
    flag_uncertain: false
  },
  {
    No: 640,
    subject: "子育て支援の拡充",
    link: "https://github.com/team-mirai/policy/pull/640",
    label: "子育て",
    body: null,
    summary: null,
    stance_val: 3.2,
    assert_val: 2.8,
    category: "肯定的",
    priority: "High",
    flag_positive: true,
    flag_negative: false,
    flag_neutral: false,
    flag_strong: false,
    flag_moderate: true,
    flag_weak: false,
    flag_assertive: true,
    flag_mild: false,
    flag_uncertain: false
  },
  {
    No: 400,
    subject: "コミュニティ支援策",
    link: "https://github.com/team-mirai/policy/pull/400",
    label: "社会保障",
    body: null,
    summary: null,
    stance_val: 1.8,
    assert_val: 1.5,
    category: "肯定的",
    priority: "Medium",
    flag_positive: true,
    flag_negative: false,
    flag_neutral: false,
    flag_strong: false,
    flag_moderate: false,
    flag_weak: true,
    flag_assertive: false,
    flag_mild: true,
    flag_uncertain: false
  },
  {
    No: 260,
    subject: "ひとり親世帯支援",
    link: "https://github.com/team-mirai/policy/pull/260",
    label: "社会保障",
    body: null,
    summary: null,
    stance_val: 2.7,
    assert_val: 3.5,
    category: "肯定的",
    priority: "High",
    flag_positive: true,
    flag_negative: false,
    flag_neutral: false,
    flag_strong: false,
    flag_moderate: true,
    flag_weak: false,
    flag_assertive: true,
    flag_mild: false,
    flag_uncertain: false
  },
  {
    No: 1240,
    subject: "高齢者運転免許制度",
    link: "https://github.com/team-mirai/policy/pull/1240",
    label: "交通安全",
    body: null,
    summary: null,
    stance_val: -0.5,
    assert_val: 2.2,
    category: "中立",
    priority: "Medium",
    flag_positive: false,
    flag_negative: false,
    flag_neutral: true,
    flag_strong: false,
    flag_moderate: true,
    flag_weak: false,
    flag_assertive: true,
    flag_mild: false,
    flag_uncertain: false
  },
  {
    No: 1360,
    subject: "公的身元保証制度",
    link: "https://github.com/team-mirai/policy/pull/1360",
    label: "社会保障",
    body: null,
    summary: null,
    stance_val: 3.8,
    assert_val: 4.0,
    category: "強い肯定",
    priority: "High",
    flag_positive: true,
    flag_negative: false,
    flag_neutral: false,
    flag_strong: true,
    flag_moderate: false,
    flag_weak: false,
    flag_assertive: true,
    flag_mild: false,
    flag_uncertain: false
  }
]

export async function loadPRDashboardData(): Promise<PRDashboardData[]> {
  return samplePRData
}
