import type { VoronoiPolygon } from '@/type';

interface VoronoiData {
  polygons: VoronoiPolygon[];
  metadata: {
    generated_at: string;
    source_file: string;
    polygon_count: number;
  };
}

/**
 * Load pre-generated Voronoi polygons from JSON file
 * This assumes polygons were generated by the Python script
 */
export async function loadVoronoiPolygons(): Promise<VoronoiPolygon[]> {
  try {
    const response = await fetch('/data/voronoi_polygons.json');
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    
    const data: VoronoiData = await response.json();
    console.log(`Loaded ${data.polygons.length} pre-generated polygons`);
    return data.polygons;
  } catch (error) {
    console.error('Failed to load Voronoi polygons:', error);
    return [];
  }
}

/**
 * Check if pre-generated polygons are available
 */
export async function checkVoronoiPolygonsAvailable(): Promise<boolean> {
  try {
    const response = await fetch('/data/voronoi_polygons.json', { method: 'HEAD' });
    return response.ok;
  } catch {
    return false;
  }
}

/**
 * Convert polygon coordinates to Plotly path format
 */
export function polygonToPlotlyPath(coordinates: number[][][]): string {
  if (!coordinates || coordinates.length === 0) return '';
  
  const paths = coordinates.map(ring => {
    const pathCommands = ring.map((point, index) => 
      index === 0 ? `M ${point[0]} ${point[1]}` : `L ${point[0]} ${point[1]}`
    ).join(' ') + ' Z';
    return pathCommands;
  });
  
  return paths.join(' ');
}
